name: Deploy to Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Get dependencies
        run: |
          go get
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build binary and zip
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o thought-jar . && zip deployment.zip thought-jar
      - name: deploy
        run: |
          aws lambda update-function-code --function-name=thought-jar --zip-file=fileb://deployment.zip
